### ISSUE TITLE
chore: add license

### ISSUE THREAD

**Issue by 4x4notfound** [proofzero/go-ipld-linkstore#1]

**Comment by nathannaveen** [comment]
I would like to work on this, I am new to OSS could you please give me a few pointers to where and how I can address this issue? Thanks

**Comment by alfl** [comment]
Done!

**Comment by alfl** [comment]
> I would like to work on this, I am new to OSS could you please give me a few pointers to where and how I can address this issue? Thanks

See LICENSE here -- this was more of an internal project thing because we had to choose a particular license. Thanks for your interest!
